//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributoProducto
    {
        public string ContenidoTexto { get; set; }
        public byte[] ContenidoBinario { get; set; }
        public Nullable<int> ContenidoEntero { get; set; }
        public int Atributo { get; set; }
        public int Producto { get; set; }
        public Nullable<double> ContenidoReal { get; set; }
        public Nullable<bool> ContenidoBoolean { get; set; }
    
        public virtual Atributo Atributo1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
