//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atributo
    {
        public Atributo()
        {
            this.AtributoProducto = new HashSet<AtributoProducto>();
        }
    
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public int ID { get; set; }
    
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual ICollection<AtributoProducto> AtributoProducto { get; set; }

        public override string ToString()
        {
            return Nombre;
        }
    }
}
