//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaP
    {
        public CategoriaP()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public string Nombre { get; set; }
        public int Cuenta { get; set; }
        public int ID { get; set; }
    
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }

        public override string ToString()
        {
            return Nombre;
        }

        public override bool Equals(object obj)
        {
            bool ok = false;

            if (obj is CategoriaP)
            {
                CategoriaP nuevo = (CategoriaP)obj;
                if (nuevo.ID.Equals(this.ID))
                {
                    ok = true;
                }
            }
            return ok;
        }
    }
}
