//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.Atributo = new HashSet<Atributo>();
            this.CategoriaP = new HashSet<CategoriaP>();
            this.Producto = new HashSet<Producto>();
            this.Relaciones = new HashSet<Relaciones>();
        }
    
        public string Nombre { get; set; }
        public byte[] Logo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<Atributo> Atributo { get; set; }
        public virtual ICollection<CategoriaP> CategoriaP { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Relaciones> Relaciones { get; set; }

        public override string ToString()
        {
            return Nombre;
        }
    }
}
