//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.AtributoProducto = new HashSet<AtributoProducto>();
            this.Relaciones_Productos = new HashSet<Relaciones_Productos>();
            this.Relaciones_Productos1 = new HashSet<Relaciones_Productos>();
            this.CategoriaP = new HashSet<CategoriaP>();
        }
    
        public string SKU { get; set; }
        public string GTIN { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Label { get; set; }
        public byte[] Thumbnail { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<AtributoProducto> AtributoProducto { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual ICollection<Relaciones_Productos> Relaciones_Productos { get; set; }
        public virtual ICollection<Relaciones_Productos> Relaciones_Productos1 { get; set; }
        public virtual ICollection<CategoriaP> CategoriaP { get; set; }

        public override string ToString()
        {
            return this.Label;
        }

        public override bool Equals(object obj)
        {
            // Si el objeto es null o no es del tipo Producto, retornamos false.
            if (obj == null || GetType() != obj.GetType())
                return false;

            Producto otroProducto = (Producto)obj;

            // Comparamos los ID de los productos.
            return this.ID == otroProducto.ID;
        }

        public override int GetHashCode()
        {
            return this.ID.GetHashCode();  // O la propiedad que utilices como identificador único
        }
    }
}
