//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones
    {
        public Relaciones()
        {
            this.Relaciones_Productos = new HashSet<Relaciones_Productos>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int CuentaID { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<Relaciones_Productos> Relaciones_Productos { get; set; }

        public override string ToString()
        {
            return this.Nombre;
        }
    }
}
