//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grupo21DBEntities : DbContext
    {
        public grupo21DBEntities()
            : base("name=grupo21DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Atributo> Atributo { get; set; }
        public DbSet<AtributoProducto> AtributoProducto { get; set; }
        public DbSet<CategoriaP> CategoriaP { get; set; }
        public DbSet<Cuenta> Cuenta { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Relaciones> Relaciones { get; set; }
        public DbSet<Relaciones_Productos> Relaciones_Productos { get; set; }
    }
}
